name: bbxyapp
description: BBXYApp - 基于 FlClash 的 SSPanel 四端代理管理应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # UI & Theme
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.11.1
  
  # HTTP & Network
  dio: ^5.8.0
  
  # Local Storage
  shared_preferences: ^2.5.3
  path_provider: ^2.1.0
  
  # Windows Platform
  window_manager: ^0.5.0
  screen_retriever: ^0.2.0
  
  # Utils
  path: ^1.9.0
  json_annotation: ^4.9.0
  crypto: ^3.0.3
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700 