name: bbxyapp
description: BBXYApp - 基于 FlClash 的 SSPanel 四端代理管理应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.0
  path: ^1.9.0
  shared_preferences: ^2.5.3
  window_manager: ^0.5.0
  dynamic_color: ^1.7.0
  launch_at_startup: ^0.5.1
  json_annotation: ^4.9.0
  file_picker: ^8.0.3
  mobile_scanner: ^7.0.0
  app_links: ^6.4.0
  win32_registry: ^2.0.0
  tray_manager: ^0.5.0
  collection: ^1.18.0
  animations: ^2.0.11
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  freezed_annotation: ^2.4.1
  image_picker: ^1.1.2
  webdav_client: ^1.2.2
  dio: ^5.8.0+1
  win32: ^5.5.1
  ffi: ^2.1.2
  archive: ^3.6.1
  lpinyin: ^2.0.3
  emoji_regex: ^0.0.5
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^11.3.3
  connectivity_plus: ^6.1.0
  screen_retriever: ^0.2.0
  defer_pointer: ^0.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1
  material_color_utilities: ^0.11.1
  flutter_svg: ^2.1.0
  flutter_cache_manager: ^3.4.1
  crypto: ^3.0.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.13
  args: ^2.4.2
  freezed: ^2.5.1
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        - asset: assets/fonts/NotoSansSC-Bold.ttf
          weight: 700 